apiVersion: platform.enterprise.stacklok.com/v1alpha1
kind: ClusterPlatformRole
metadata:
  name: my-clusterplatformrole
spec:
  productActions:
    - actions:
        - <string>
      apiGroup: <string>
