apiVersion: platform.enterprise.stacklok.com/v1alpha1
kind: ClusterPlatformRoleBinding
metadata:
  name: my-clusterplatformrolebinding
spec:
  bindings:
    - from:
        - {}
      roleRef:
        kind: ClusterPlatformRole
        name: <string>
