apiVersion: platform.enterprise.stacklok.com/v1alpha1
kind: PlatformRoleBinding
metadata:
  name: my-platformrolebinding
  namespace: default
spec:
  bindings:
    - from:
        - {}
      roleRef:
        kind: ClusterPlatformRole
        name: <string>
