// SPDX-FileCopyrightText: Copyright 2026 Stacklok, Inc.
// SPDX-License-Identifier: Apache-2.0

// AUTO-GENERATED by scripts/generate-crd-barrel.mjs. Do not edit.
// Consolidated map of every CRD Kind to its extracted JSON Schema, across all
// CRD sets declared in .github/upstream-projects.yaml. Consumed by the
// <CRDFields> React component; the <CRDReference> remark plugin reads the same
// schemas from disk at build time. Regenerate with extract-crds.mjs or
// `node scripts/generate-crd-barrel.mjs`.

import ClusterPlatformRole from '@site/static/api-specs/enterprise-crds/clusterplatformroles.schema.json';
import ClusterPlatformRoleBinding from '@site/static/api-specs/enterprise-crds/clusterplatformrolebindings.schema.json';
import EmbeddingServer from '@site/static/api-specs/toolhive-crds/embeddingservers.schema.json';
import MCPAuthzConfig from '@site/static/api-specs/toolhive-crds/mcpauthzconfigs.schema.json';
import MCPExternalAuthConfig from '@site/static/api-specs/toolhive-crds/mcpexternalauthconfigs.schema.json';
import MCPGroup from '@site/static/api-specs/toolhive-crds/mcpgroups.schema.json';
import MCPOIDCConfig from '@site/static/api-specs/toolhive-crds/mcpoidcconfigs.schema.json';
import MCPRegistry from '@site/static/api-specs/toolhive-crds/mcpregistries.schema.json';
import MCPRemoteProxy from '@site/static/api-specs/toolhive-crds/mcpremoteproxies.schema.json';
import MCPServer from '@site/static/api-specs/toolhive-crds/mcpservers.schema.json';
import MCPServerEntry from '@site/static/api-specs/toolhive-crds/mcpserverentries.schema.json';
import MCPTelemetryConfig from '@site/static/api-specs/toolhive-crds/mcptelemetryconfigs.schema.json';
import MCPToolConfig from '@site/static/api-specs/toolhive-crds/mcptoolconfigs.schema.json';
import MCPWebhookConfig from '@site/static/api-specs/toolhive-crds/mcpwebhookconfigs.schema.json';
import PlatformRoleBinding from '@site/static/api-specs/enterprise-crds/platformrolebindings.schema.json';
import ToolhiveAuthorizationPolicy from '@site/static/api-specs/enterprise-crds/toolhiveauthorizationpolicies.schema.json';
import VirtualMCPCompositeToolDefinition from '@site/static/api-specs/toolhive-crds/virtualmcpcompositetooldefinitions.schema.json';
import VirtualMCPServer from '@site/static/api-specs/toolhive-crds/virtualmcpservers.schema.json';

export const allSchemas = {
  ClusterPlatformRole,
  ClusterPlatformRoleBinding,
  EmbeddingServer,
  MCPAuthzConfig,
  MCPExternalAuthConfig,
  MCPGroup,
  MCPOIDCConfig,
  MCPRegistry,
  MCPRemoteProxy,
  MCPServer,
  MCPServerEntry,
  MCPTelemetryConfig,
  MCPToolConfig,
  MCPWebhookConfig,
  PlatformRoleBinding,
  ToolhiveAuthorizationPolicy,
  VirtualMCPCompositeToolDefinition,
  VirtualMCPServer,
} as const;

export type AnyCRDKind = keyof typeof allSchemas;
