// AUTO-GENERATED by scripts/generate-crd-pages.mjs. Do not edit.
// Maps each CRD Kind to its extracted JSON Schema so <CRDFields> and the
// <CRDReference> remark plugin can resolve schemas by Kind name.

import EmbeddingServer from '@site/static/api-specs/crds/embeddingservers.schema.json';
import MCPExternalAuthConfig from '@site/static/api-specs/crds/mcpexternalauthconfigs.schema.json';
import MCPGroup from '@site/static/api-specs/crds/mcpgroups.schema.json';
import MCPOIDCConfig from '@site/static/api-specs/crds/mcpoidcconfigs.schema.json';
import MCPRegistry from '@site/static/api-specs/crds/mcpregistries.schema.json';
import MCPRemoteProxy from '@site/static/api-specs/crds/mcpremoteproxies.schema.json';
import MCPServerEntry from '@site/static/api-specs/crds/mcpserverentries.schema.json';
import MCPServer from '@site/static/api-specs/crds/mcpservers.schema.json';
import MCPTelemetryConfig from '@site/static/api-specs/crds/mcptelemetryconfigs.schema.json';
import MCPToolConfig from '@site/static/api-specs/crds/mcptoolconfigs.schema.json';
import MCPWebhookConfig from '@site/static/api-specs/crds/mcpwebhookconfigs.schema.json';
import VirtualMCPCompositeToolDefinition from '@site/static/api-specs/crds/virtualmcpcompositetooldefinitions.schema.json';
import VirtualMCPServer from '@site/static/api-specs/crds/virtualmcpservers.schema.json';

export const schemas = {
  EmbeddingServer,
  MCPExternalAuthConfig,
  MCPGroup,
  MCPOIDCConfig,
  MCPRegistry,
  MCPRemoteProxy,
  MCPServerEntry,
  MCPServer,
  MCPTelemetryConfig,
  MCPToolConfig,
  MCPWebhookConfig,
  VirtualMCPCompositeToolDefinition,
  VirtualMCPServer,
} as const;

export type CRDKind = keyof typeof schemas;
