name: Documentation error
description: Report incorrect, outdated, or unclear documentation
title: '[Bug]: '
labels: ['documentation', 'bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve the documentation! Please provide as much detail as possible about the issue you found.

  - type: input
    id: page
    attributes:
      label: Page or section
      description: Which page or section has the issue? Paste the URL or describe the location.
      placeholder: 'https://docs.stacklok.com/...'
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's wrong?
      description: Describe the error or problem you found. Is the content incorrect, outdated, confusing, or missing important details?
      placeholder: 'The example code shows X, but it should be Y because...'
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested fix
      description: If you have a suggestion for how to fix or improve this, please share it here.
      placeholder: 'The documentation should say... or The example should show...'
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or information that might be helpful.
    validations:
      required: false
