name: Documentation gap
description: Request documentation for features or functionality that aren't currently covered
title: '[Gap]: '
labels: ['documentation', 'enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for identifying missing documentation! Help us understand what needs to be documented.

  - type: textarea
    id: what
    attributes:
      label: What needs documentation?
      description: Describe the feature, functionality, or topic that needs documentation.
      placeholder: 'The new X feature... or How to configure Y... or Best practices for Z...'
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context and references
      description: If this relates to a new feature or change, please provide links to relevant issues, PRs, or other context.
      placeholder: 'See https://github.com/stacklok/toolhive/pull/123 or This was discussed in...'
    validations:
      required: false

  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: Help us understand why this documentation is needed. What are you trying to accomplish?
      placeholder: 'As a user, I want to... or This would help when...'
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other information that might be helpful.
    validations:
      required: false
