name: Documentation enhancement
description: Suggest improvements to existing documentation
title: '[Enhancement]: '
labels: ['documentation', 'enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us make the documentation better! Please share your ideas for improving existing content.

  - type: input
    id: page
    attributes:
      label: Page or section
      description: Which page or section could be improved? Paste the URL or describe the location.
      placeholder: 'https://docs.stacklok.com/...'
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: What could be better?
      description: Describe what's currently missing or could be improved. What would make this content more helpful?
      placeholder: 'This section could benefit from... or It would be helpful to include...'
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed improvement
      description: If you have specific ideas for how to improve this content, please share them here.
      placeholder: 'Add a section about... or Include an example showing... or Reorganize the content to...'
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, examples, or information that might be helpful.
    validations:
      required: false
