apiVersion: ai-gateway.stacklok.dev/v1alpha1
kind: AIGateway
metadata:
  name: my-aigateway
  namespace: default
spec:
  auth: {}
  gateway:
    listeners:
      - port: 0
  providers:
    - credentials:
        type: APIKey
      endpoint:
        hostname: <string>
      name: <string>
      schema: OpenAI
  routes:
    - backendRefs:
        - provider: <string>
      name: <string>
