name: Static checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: Lint and format checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run ESLint
        run: npm run eslint

      - name: Run Prettier
        run: npm run prettier
