name: On PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  security:
    name: Security checks
    uses: ./.github/workflows/_security-checks.yaml

  static-checks:
    name: Static checks
    uses: ./.github/workflows/_static-checks.yaml
